# Generated by Django 5.0.7 on 2024-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech')], default='btech'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profileimg',
            field=models.ImageField(default='blank_user.png', upload_to='student'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('it', 'Information technology'), ('me', 'Mechanical'), ('cv', 'Civil'), ('eee', 'Electronics and Electrical'), ('ece', 'Electronics and Communication'), ('ch', 'Chemical'), ('cse', 'Computer Science')]),
        ),
    ]
