# Generated by Django 5.0.7 on 2024-07-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_alter_studentprofile_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='degree',
        ),
    ]
