# Generated by Django 5.0.7 on 2024-07-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_remove_studentprofile_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(default='blank_user.png', upload_to='company'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='type_of_company',
            field=models.CharField(blank=True, choices=[('service', 'service'), ('product', 'product')]),
        ),
    ]
