# Generated by Django 5.0.7 on 2024-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_companyprofile_desc_companyprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='type_of_company',
            field=models.CharField(blank=True, choices=[('service', 'service based'), ('product', 'product based')]),
        ),
    ]
