# Generated by Django 5.0.7 on 2024-07-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_alter_companyprofile_type_of_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('IT', 'Information technology'), ('ME', 'Mechanical'), ('CV', 'Civil'), ('EEE', 'Electronics and Electrical'), ('ECE', 'Electronics and Communication'), ('CH', 'Chemical'), ('CSE', 'Computer Science')]),
        ),
    ]
