# Generated by Django 5.0.7 on 2024-07-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_alter_studentprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech')]),
        ),
    ]
