# Generated by Django 5.0.7 on 2024-08-06 13:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_studentprofile_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('bond_years', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('requirement', models.TextField(blank=True)),
                ('closing_date', models.DateField(blank=True, default=datetime.date(2024, 12, 31))),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.companyprofile')),
            ],
        ),
    ]
