# Generated by Django 5.0.7 on 2024-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0010_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
