# Generated by Django 5.0.7 on 2024-08-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0012_alter_appliedjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
